services:
  # Ludus GUI - Next.js Application
  ludus-gui:
    build:
      context: ./ludus-gui
      dockerfile: Dockerfile
    container_name: ludus-gui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LUDUS_API_BASE_URL=${LUDUS_API_BASE_URL:-http://localhost:8080}
      - LUDUS_API_KEY=${LUDUS_API_KEY:-demo-key}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NEXT_PUBLIC_DISABLE_AUTH=true
    networks:
      - ludus-network
    restart: unless-stopped

  # Shell-n-Slides - Static Web Server
  shell-n-slides:
    build:
      context: ./shell-n-slides
      dockerfile: Dockerfile
    container_name: shell-n-slides
    ports:
      - "8000:8000"
    networks:
      - ludus-network
    restart: unless-stopped

# Note: ttyd runs on the host system to access Kali CLI
# Run: ttyd -p 7681 -t fontSize=18 -t 'theme={"background": "#1e1e1e"}' -W /bin/bash

networks:
  ludus-network:
    driver: bridge